name: Home - Ansible Apply - Kubernetes

on:
  push:
    branches:
        - main
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/kubernetes.yml"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  kubernetes-ansible-apply:
    uses: ./.github/workflows/reusable-ansible-apply.yml
    with:
      working-directory: ansible
      concurrency-group: home-ansible-kubernetes
      runner: '["self-hosted", "linux", "terraform", "dev"]'
      ansible-playbook: kubernetes
      ansible-group: k8s_cluster

    secrets:
      ansible_ssh_private_key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
