---
ansible_python_interpreter: /usr/bin/python3

# SSH configuration
# ansible_user: ansible
# ansible_ssh_private_key_file: ~/.ssh/id_ed25519_ansible
# ansible_ssh_common_args: "-o IdentitiesOnly=yes"

# Privilege escalation
# ansible_become: true
# ansible_become_method: sudo

domain_name: home.arpa

docker_users:
  - rs
  - ansible

linux_users:
  - name: rs
    comment: "Admin"
    group: rs
    uid: 1001
    gid: 1001
    create_home: true
    home: /home/rs
    system: false
    shell: /bin/bash
    groups:
      - sudo
    ssh_key: "{{ ssh_key_rs }}"
    sudo_nopasswd: true

  - name: ansible
    comment: "Ansible Automation"
    group: ansible
    uid: 1000
    gid: 1000
    create_home: true
    home: /home/ansible
    system: false
    shell: /bin/bash
    groups:
      - sudo
    ssh_key: "{{ ssh_key_ansible }}"
    sudo_nopasswd: true

cifs_mounts:
  - server: "truenas.{{ domain_name }}"
    share: common
    mount_point: /mnt/common
    username: common
    password: "{{ smb_common_password }}"
    options:
      - uid=1500
      - gid=1500
      - _netdev
      - x-systemd.automount
      - iocharset=utf8
      - vers=3.1.1
      - serverino
      - cache=strict
      - actimeo=1
      - noperm