---
- name: Install Syncthing (state=present is optional)
  ansible.builtin.apt:
    name: syncthing
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Install syncthing systemd service
  ansible.builtin.template:
    src: syncthing.service.j2
    dest: /etc/systemd/system/syncthing.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Systemd daemon reload
    - Systemd enable syncthing
    - Systemd restart syncthing
