---
all:
  children:

    # AWS environment
    aws:
       children:

         # EC2 instances
         ec2:
           hosts:
             website:
               ansible_host: ec2-51-20-142-2.eu-north-1.compute.amazonaws.com
