---
all:
  vars:
    ansible_user: ansible

  children:

    # AWS environment
    aws:
      children:

        # EC2 instances
        ec2:
          hosts:
            project_website:
              ansible_host: ec2-16-171-64-75.eu-north-1.compute.amazonaws.com
