---
linux_users:
  - name: rs
    comment: "Admin Account"
    group: rs
    uid: 1001
    gid: 1001
    create_home: true
    home: /home/rs
    system: false
    shell: /bin/bash
    groups:
      - sudo
    ssh_key: "{{ ssh_key_rs }}"
    sudo_nopasswd: true

  - name: ansible
    comment: "Ansible Automation"
    group: ansible
    uid: 1000
    gid: 1000
    create_home: true
    home: /home/ansible
    system: false
    shell: /bin/bash
    groups:
      - sudo
    ssh_key: "{{ ssh_key_ansible }}"
    sudo_nopasswd: true
