---
linux_users:
  - name: rs
    comment: "Admin"
    uid: 1001
    group: rs
    gid: 1001
    create_home: true
    home: /home/rs
    system: false
    shell: /bin/bash
    groups:
      - sudo
    ssh_key: "{{ ssh_key_rs }}"
    sudo_nopasswd: true

cifs_mounts:
  - server: "truenas.{{ domain_name }}"
    share: common
    mount_point: /mnt/common
    username: common
    password: "{{ smb_common_password }}"
