---
- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Systemd enable qbittorrent
  ansible.builtin.systemd_service:
    name: qbittorrent
    enabled: true

- name: Systemd restart qbittorrent
  ansible.builtin.systemd_service:
    name: qbittorrent
    state: restarted
