---
- name: Bootstrap container
  hosts: github-runner
  become: false
  vars:
    ansible_user: root

  roles:
    - bootstrap_lxc

- name: Configure Linux users
  hosts: github-runner
  become: false
  vars:
    ansible_user: root

  roles:
    - linux_users

- name: Install and configure GitHub runner
  hosts: github-runner
  become: true
  
  roles:
    - actions-runner