---
- name: Configure Linux users
  hosts: k8s_cluster
  become: true
  roles:
    - linux_users

- import_playbook: ../../dependencies/kubespray/playbooks/cluster.yml

- name: Configure kubectl
  hosts: kube_control_plane
  become: true
  roles:
    - kubeconfig_remote

# - name: Ensure kubectl access from local machine.
#   hosts: k8s-cp1
#   roles:
#     - kubeconfig_local
#   vars:
#     local_owner: rs
#     local_group: rs
#     local_home: /home/rs