---
- name: Bootstrap Proxmox VM
  hosts: k8s_cluster
  become: true
  roles:
    - common
    - linux_users

# Deploy Kubernetes cluster with Kubespray
- import_playbook: ../../dependencies/kubespray/playbooks/cluster.yml

- name: Configure kubectl
  hosts: kube_control_plane
  become: true
  roles:
    - kubeconfig_remote
