---
- name: Bootstrap minecraft VM
  hosts: minecraft
  become: true

  roles:
    - linux_users
    - cifs_mount

# - name: Install and configure Minecraft server
#   hosts: minecraft
#   become: true

#   roles:
#     - minecraft
