---
- name: Bootstrap container
  hosts: pve-exporter
  become: false
  vars:
    ansible_user: root
  roles:
    - bootstrap_lxc

- name: Configure Linux users
  hosts: pve-exporter
  become: false
  vars:
    ansible_user: root
  roles:
    - linux_users
