---
- name: Bootstrap Proxmox VM
  hosts: monitoring
  become: true
  roles:
    - common
    - linux_users

- name: Deploy prometheus-pve-exporter
  hosts: pve-exporter
  become: true
  roles:
    - prometheus-pve-exporter
