---
# Caddy Configuration
caddy_sites:
  - domains:
      - aws.01011101.xyz
      - www.aws.01011101.xyz
    upstream: 127.0.0.1:8080

# Dockerized Service Configuration
docker_image: "docker.io/rs235/website:latest"
docker_container: rs235/website:latest
docker_ports:
  - "127.0.0.1:8081:8080"
