---
- name: Add Caddy Repository
  deb822_repository:
    name: caddy
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/stable/deb/ubuntu
    suites: '{{ ansible_distribution_release }}'
    components: main
    signed_by: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy