---
helm_enabled: true

registry_enabled: false

metrics_server_enabled: true

local_path_provisioner_enabled: false

local_volume_provisioner_enabled: false

gateway_api_enabled: false

ingress_alb_enabled: false

cert_manager_enabled: true

metallb_enabled: true

metallb_config:

  address_pools:
    primary:
      ip_range:
        - 10.10.10.40-10.10.10.50
      auto_assign: true

  layer2:
    - primary

argocd_enabled: false
argocd_version: v2.14.21
argocd_install_url: https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml
argocd_install_checksum: sha256:ee39d40847bbb36154ebcdf2f5c93e0a9001ab60131afb60dbe42981a069699e

kube_vip_enabled: true
kube_vip_arp_enabled: true
kube_vip_controlplane_enabled: true
kube_vip_address: 10.10.10.30
loadbalancer_apiserver:
  address: "{{ kube_vip_address }}"
  port: 6443

node_feature_discovery_enabled: false