---
name: AWS - Ansible Apply - aws-website

on:
  push:
    branches:
      - main
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/aws_website.yml"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-apply-aws-website:
    uses: ./.github/workflows/reusable-ansible-apply.yml
    with:
      working-directory: ansible
      concurrency-group: home-ansible-aws-website
      runner: '["ubuntu-latest"]'
      ansible-playbook: aws_website
      ansible-inventory-group: ec2

    secrets:
      ansible_ssh_private_key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
