name: AWS - Terraform Apply - website

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/aws/website/**"
      - "terraform/modules/proxmox/**"

  workflow_dispatch:

jobs:
  website-terraform-apply:
    uses: ./.github/workflows/template-terraform-apply.yml
    with:
      working-directory: terraform/environments/aws/website
      concurrency-group: terraform-aws-website
    secrets: inherit
