name: AWS - Terraform Plan - project

on:
  pull_request:
    paths:
      - "terraform/environments/aws/project/**"
      - "terraform/modules/aws/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  project-terraform-plan:
    uses: ./.github/workflows/aws-template-terraform-plan.yml
    with:
      working-directory: terraform/environments/aws/project
      concurrency-group: terraform-aws-project
    secrets: inherit
