name: AWS - Terraform Plan - project

on:
  pull_request:
    paths:
      - "terraform/environments/aws/project/**"
      - "terraform/modules/aws/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  project-terraform-plan:
    uses: ./.github/workflows/reusable-terraform-plan.yml
    with:
      working-directory: terraform/environments/aws/project
      concurrency-group: aws-terraform-project
      runner: '["ubuntu-latest"]'
      ansible_ssh_public_key: ${{ vars.ANSIBLE_SSH_PUBLIC_KEY }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
