---
name: AWS - Terraform Apply - project

on:
  push:
    branches:
      - main
    paths:
      - "terraform/environments/aws/project/**"
      - "terraform/modules/proxmox/**"

  workflow_dispatch:

jobs:
  terraform-apply-project:
    uses: ./.github/workflows/reusable-terraform-apply.yml
    with:
      working-directory: terraform/environments/aws/project
      concurrency-group: aws-website
      runner: '["self-hosted", "Linux", "X64", "infra", "home"]'
      # Ansible SSH private key to be injected during AWS instance creation for secure automation access.
      ansible_ssh_public_key: ${{ vars.ANSIBLE_SSH_PUBLIC_KEY }}
    secrets:
      # AWS credentials
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
