---
name: AWS - Ansible Check - aws-website

on:
  pull_request:
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/aws-website.yml"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-check-networking:
    uses: ./.github/workflows/reusable-ansible-check.yml
    with:
      working-directory: ansible
      concurrency-group: home-ansible-aws-website
      runner: '["ubuntu-latest"]'
      ansible-playbook: aws-website
      ansible-inventory-group: project_ec2

    secrets:
      ansible_ssh_private_key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
