---
name: AWS - Terraform Apply - project

on:
  push:
    branches:
      - main
    paths:
      - "terraform/environments/aws/project/**"
      - "terraform/modules/proxmox/**"

  workflow_dispatch:

jobs:
  project-terraform-apply:
    uses: ./.github/workflows/reusable-terraform-apply.yml
    with:
      working-directory: terraform/environments/aws/project
      concurrency-group: aws-terraform-project
      runner: '["self-hosted", "Linux", "X64", "infra", "home"]'
      ansible_ssh_public_key: ${{ vars.ANSIBLE_SSH_PUBLIC_KEY }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
