---
name: Home - Ansible Check - networking

on:
  pull_request:
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/networking.yml"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-check-networking:
    uses: ./.github/workflows/reusable-ansible-check.yml
    with:
      working-directory: ansible
      concurrency-group: home-networking
      runner: '["self-hosted", "Linux", "X64", "infra", "home"]'
      environment: home
      ansible-playbook: networking
      ansible-inventory-group: networking

    secrets:
      ansible_ssh_private_key: ${{ secrets.HOME_ANSIBLE_SSH_PRIVATE_KEY }}
      ansible_vault_password: ${{ secrets.HOME_ANSIBLE_VAULT_PASSWORD }}
