name: Monitoring Ansible Apply

on:
  push:
    branches:
        - main
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/monitoring.yml**"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  monitoring-ansible-apply:
    uses: ./.github/workflows/template-ansible-apply.yml
    with:
      working-directory: ansible
      concurrency-group: ansible-home-monitoring
      ansible-playbook: monitoring
      ansible-group: monitoring
    secrets: inherit