name: Monitoring Ansible Check

on:
  pull_request:
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/monitoring.yml**"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  monitoring-ansible-check:
    uses: ./.github/workflows/template-ansible-check.yml
    with:
      working-directory: ansible
      concurrency-group: ansible-home-monitoring
      ansible-playbook: monitoring
      ansible-group: monitoring
    secrets: inherit