---
name: Home - Ansible Apply - networking

on:
  push:
    branches:
      - main
    paths:
      - "ansible/inventories/home/**"
      - "ansible/playbooks/networking.yml"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-apply-networking:
    uses: ./.github/workflows/reusable-ansible-apply.yml
    with:
      working-directory: ansible
      concurrency-group: home-ansible-networking
      runner: '["self-hosted", "Linux", "X64", "infra", "home"]'
      ansible-playbook: networking
      ansible-inventory-group: networking

    secrets:
      ansible_ssh_private_key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
