---
name: Home - Terraform Apply - kubernetes

on:
  push:
    branches:
      - main
    paths:
      - "terraform/environments/home/kubernetes/**"
      - "terraform/modules/proxmox/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-apply-kubernetes:
    uses: ./.github/workflows/reusable-terraform-apply.yml
    with:
      working-directory: terraform/environments/home/kubernetes
      concurrency-group: home-kubernetes
      runner: '["self-hosted", "Linux", "X64", "infra", "home"]'
      # Disables TLS certificate verification for Proxmox BPG provider. Only acceptable during development.
      proxmox_ve_insecure: ${{ vars.PROXMOX_VE_INSECURE }}
    secrets:
      # Proxmox VE API token
      proxmox_ve_endpoint: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      proxmox_ve_api_token: ${{ secrets.PROXMOX_VE_API_TOKEN }}
