name: Kubernetes Terraform Apply

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/home/kubernetes/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  kubernetes-terraform-apply:
    uses: ./.github/workflows/template-terraform-apply.yml
    with:
      working-directory: terraform/environments/home/kubernetes
      # ansible-playbook: kubernetes
      # ansible-group: k8s_cluster
      concurrency-group: terraform-home-kubernetes
    secrets: inherit