name: Kubernetes Plan

on:
  pull_request:
    paths:
      - "terraform/environments/home/kubernetes/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

jobs:
  plan:
    uses: ./.github/workflows/template-terraform-plan.yml
    with:
      working-directory: terraform/environments/home/kubernetes
      ansible-playbook: kubernetes
    secrets: inherit