name: Kubernetes Terraform Apply

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/home/kubernetes/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

jobs:
  terraform-apply:
    uses: ./.github/workflows/template-terraform-apply.yml
    with:
      working-directory: terraform/environments/home/kubernetes
      ansible-playbook: kubernetes
      ansible-group: k8s_cluster
      concurrency-group: terraform-home-kubernetes
    secrets: inherit

  ansible-check:
    needs: terraform-apply
    uses: ./.github/workflows/template-ansible-check.yml
    with:
      ansible-playbook: kubernetes
      ansible-group: k8s_cluster
      concurrency-group: ansible-home-kubernetes
    secrets: inherit

  ansible-apply:
      needs: ansible-check
      uses: ./.github/workflows/template-ansible-apply.yml
      with:
        ansible-playbook: kubernetes
        ansible-group: k8s_cluster
        concurrency-group: ansible-home-kubernetes
      secrets: inherit