name: Monitoring Terraform Apply

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/home/monitoring/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

  workflow_dispatch:

jobs:
  monitoring-terraform-apply:
    uses: ./.github/workflows/template-terraform-apply.yml
    with:
      working-directory: terraform/environments/home/monitoring
      # ansible-playbook: monitoring
      # ansible-group: monitoring
      concurrency-group: terraform-home-monitoring
    secrets: inherit