---
name: Reusable Ansible Apply

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      concurrency-group:
        required: true
        type: string

      runner:
        required: true
        type: string

      ansible-playbook:
        required: true
        type: string

      ansible-inventory-group:
        required: true
        type: string

      environment:
        required: true
        type: string

    secrets:
      ansible_ssh_private_key:
        required: true

      ansible_vault_password:
        required: true

concurrency:
  group: ${{ inputs.concurrency-group }}
  cancel-in-progress: false

jobs:
  reusable-ansible-apply:
    name: Ansible Apply
    runs-on: ${{ fromJSON(inputs.runner) }}
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Clean workspace on self hosted runner
        # Override working directory for this step to ensure entire workspace is cleaned.
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf "${GITHUB_WORKSPACE:?}"/*
          rm -rf "${GITHUB_WORKSPACE:?}"/.[!.]*
          rm -rf "${GITHUB_WORKSPACE:?}"/..?*

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          # Checkout in recursive mode to include kubespray git submodule.
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: "3.13"

      - name: Create Python virtual environment and add it to PATH
        run: |
          python -m venv "${{ runner.temp }}/venv"
          echo "${{ runner.temp }}/venv/bin" >> "$GITHUB_PATH"

      - name: Install pip
        run: python -m pip install pip==26.2.1

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

      - name: Configure SSH
        run: |
          mkdir -p "${{ runner.temp }}/.ssh"
          chmod 700 "${{ runner.temp }}/.ssh"
          printf '%s' "${{ secrets.ansible_ssh_private_key }}" > "${{ runner.temp }}/.ssh/id_ed25519_ansible"
          chmod 600 "${{ runner.temp }}/.ssh/id_ed25519_ansible"

      - name: Create vault password file
        run: |
          printf '%s' "${{ secrets.ansible_vault_password }}" > "${{ runner.temp }}/vault_pass"
          chmod 600 "${{ runner.temp }}/vault_pass"

      - name: Wait for machines
        run: |
          ansible ${{ inputs.ansible-inventory-group }} \
            -i "inventories/${{ inputs.environment }}/inventory.yml" \
            --vault-password-file "${{ runner.temp }}/vault_pass" \
            --private-key "${{ runner.temp }}/.ssh/id_ed25519_ansible" \
            -m ansible.builtin.wait_for_connection \
            -a "timeout=300"

      - name: Execute Ansible playbook
        run: |
          ansible-playbook \
          -i "inventories/${{ inputs.environment }}/inventory.yml" \
          --vault-password-file "${{ runner.temp }}/vault_pass" \
          --private-key "${{ runner.temp }}/.ssh/id_ed25519_ansible" \
          "playbooks/${{ inputs.ansible-playbook }}.yml"
