---
name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      concurrency-group:
        required: true
        type: string

      ansible_ssh_public_key:
        required: false
        type: string

      runner:
        required: true
        type: string

      proxmox_ve_insecure:
        required: false
        type: string

    secrets:
      aws_access_key_id:
        required: false

      aws_secret_access_key:
        required: false

      proxmox_ve_endpoint:
        required: false

      proxmox_ve_api_token:
        required: false

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ inputs.concurrency-group }}
  cancel-in-progress: false

jobs:
  reusable-terraform-plan:
    runs-on: ${{ fromJSON(inputs.runner) }}
    
    env:
      TF_INPUT: "0"

      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      TF_VAR_ansible_ssh_public_key: ${{ inputs.ansible_ssh_public_key }}

      PROXMOX_VE_ENDPOINT: ${{ secrets.proxmox_ve_endpoint }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.proxmox_ve_api_token }}
      PROXMOX_VE_INSECURE: ${{ inputs.proxmox_ve_insecure }}

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: "1.15.0"

      - name: Terraform fmt
        run: terraform fmt -check -recursive
          
      - name: Terraform init
        run: terraform init -input=false
        
      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform show
        run: terraform show -no-color tfplan > "${{ runner.temp }}/tfplan.txt"

      - name: Comment Terraform plan
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88
        with:
          path: "${{ runner.temp }}/tfplan.txt"

      - name: Upload Terraform plan
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: "${{ inputs.concurrency-group }}-plan"
          path: "${{ runner.temp }}/tfplan.txt"
          if-no-files-found: error
          retention-days: 14