---
name: Reusable Terraform Apply

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      concurrency-group:
        required: true
        type: string

      runner:
        required: true
        type: string

      proxmox_ve_insecure:
        required: false
        type: string

      ansible_ssh_public_key:
        required: false
        type: string

    secrets:
      aws_access_key_id:
        required: false

      aws_secret_access_key:
        required: false

      proxmox_ve_endpoint:
        required: false

      proxmox_ve_api_token:
        required: false

permissions:
  contents: read

concurrency:
  group: ${{ inputs.concurrency-group }}
  cancel-in-progress: false

jobs:
  reusable-terraform-apply:
    runs-on: ${{ fromJSON(inputs.runner) }}

    env:
      TF_INPUT: "0"

      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      TF_VAR_ansible_ssh_public_key: ${{ inputs.ansible_ssh_public_key }}

      PROXMOX_VE_ENDPOINT: ${{ secrets.proxmox_ve_endpoint }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.proxmox_ve_api_token }}
      PROXMOX_VE_INSECURE: ${{ inputs.proxmox_ve_insecure }}

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: "1.15.0"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve
