name: Sandbox Terraform Apply

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/home/sandbox/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

jobs:
  sandbox-terraform-apply:
    uses: ./.github/workflows/template-terraform-apply.yml
    with:
      working-directory: terraform/environments/home/sandbox
      ansible-playbook: sandbox
      ansible-group: sandbox
      concurrency-group: terraform-home-sandbox
    secrets: inherit