name: Sandbox Ansible Check

on:
  pull_request:
    paths:
      - "ansible/inventories/**"
      - "ansible/playbooks/**"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

permissions:
  contents: read
  pull-requests: write

jobs:
  sandbox-ansible-check:
    uses: ./.github/workflows/template-ansible-check.yml
    with:
      working-directory: ansible
      concurrency-group: ansible-home-sandbox
      ansible-playbook: sandbox
      ansible-group: sandbox
    secrets: inherit