name: Sandbox Ansible Apply

on:
  push:
    branches:
        - main
    paths:
      - "ansible/inventories/**"
      - "ansible/playbooks/**"
      - "ansible/roles/**"
      - "ansible/requirements.yml"
      - "ansible/ansible.cfg"

permissions:
  contents: read

jobs:
  sandbox-ansible-apply:
    uses: ./.github/workflows/template-ansible-apply.yml
    with:
      working-directory: ansible
      concurrency-group: ansible-home-sandbox
      ansible-playbook: sandbox
      ansible-group: sandbox
    secrets: inherit