name: Sandbox Ansible Apply

on:
  push:
    branches:
        - main
    paths:
      - "terraform/environments/home/sandbox/**"
      - "terraform/modules/proxmox/**"
      - "terraform/modules/common/**"

permissions:
  contents: read

jobs:
  plan:
    uses: ./.github/workflows/template-ansible-check.yml
    with:
      concurrency-group: ansible-home-sandbox
      ansible-playbook: sandbox
      ansible-group: sandbox
    secrets: inherit