name: Terraform Plan

on:
  pull_request:
    paths:
      - "terraform/**"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: terraform-home-sandbox
  cancel-in-progress: false

env:
  WORK_DIR: "terraform/environments/home/sandbox"

jobs:
  terraform:
    runs-on:
      - self-hosted
    
    env:
      TF_INPUT: "0"
      TF_LOG: ERROR
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      PROXMOX_VE_INSECURE: ${{ secrets.PROXMOX_VE_INSECURE }}

    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:
      - uses: actions/checkout@vd23441a48e516b6c34aea4fa41551a30e30af803

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: 1.15.0

      - name: Terraform fmt
        run: terraform fmt -check -recursive
          
      - name: Terraform init
        run: terraform init -input=false
        
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform show
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Comment Terraform plan
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88
        with:
          path: terraform/environments/home/sandbox/tfplan.txt

      - name: Upload Terraform plan
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: terraform-plan
          path: ${{ env.WORK_DIR }}/tfplan.txt

