name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: terraform-home-sandbox
  cancel-in-progress: false

jobs:
  terraform:
    runs-on:
      - self-hosted
    
    env:
      TF_INPUT: "0"
      TF_LOG: ERROR
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      PROXMOX_VE_INSECURE: ${{ secrets.PROXMOX_VE_INSECURE }}

    defaults:
      run:
        working-directory: terraform/environments/home/sandbox

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.0

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve

  ansible:
    runs-on:
      - self-hosted
    
    env:
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      PROXMOX_VE_INSECURE: ${{ secrets.PROXMOX_VE_INSECURE }}

    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@v6

      - name: Create Python virtual environment
        run: |
          python3 -m venv .venv

      - name: Install Ansible
        run: |
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install -r requirements.txt

      - name: Create vault password file
        run: |
          printf '%s' "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

      - name: Wait for machines
        run: |
          .venv/bin/ansible all \
            -i inventories/home/inventory.yml \
            -m ansible.builtin.wait_for_connection \
            -a "timeout=300"

      - name: Ansible Configure
        run: |
          .venv/bin/ansible-playbook \
          -i inventories/home/inventory.yml \
          --vault-password-file .vault_pass \
          playbooks/sandbox.yml